In [1]:
from model import *
g = Graph([1, 2, 3], [Link(1, 2, 1, 1), Link(2, 3, 2, 2)])
g.time_matrix, g.fft_matrix

(array([[ inf, 1.15,  inf],
        [ inf,  inf, 6.8 ],
        [ inf,  inf,  inf]]),
 array([[inf,  1., inf],
        [inf, inf,  2.],
        [inf, inf, inf]]))

In [2]:
g.dijkstra(1)


(array([None, 0, 1], dtype=object), array([0.  , 1.15, 7.95]))

In [3]:
demands = Demands([1, 2, 3])

In [4]:
demands.add_od_pair(1, 2, 5)

In [5]:
demands.add_od_pair(2, 3, 4)

In [6]:
problem = Problem(g, demands)

In [7]:
problem.optimal()

1 1 

1 2 

[None 0 1]
0 1
1 3 

[None 0 1]
1 2
0 1
2 1 

[None None 1]
None 0
2 2 

2 3 

[None None 1]
1 2
3 1 

[None None None]
None 0
3 2 

[None None None]
None 1
3 3 



array([[0., 5., 0.],
       [0., 0., 4.],
       [0., 0., 0.]])

In [8]:
problem.run()

/home/sihang/workspace/traffic_proj/model.py:250: RuntimeWarning: invalid value encountered in multiply
  return sum(np.reshape(self.graph.time_matrix * self.graph.flow_matrix, (1,)))


ValueError: cannot reshape array of size 9 into shape (1,)